# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: controller
        serving.knative.dev/release: devel
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: knative.dev/serving/cmd/controller
        resources:
          # Request 2x what we saw running e2e
          requests:
            cpu: 100m
            memory: 100Mi
          # Limit to 10x the request (20x the observed peak during e2e)
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8008
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        # Used for Stackdriver only.
        # knative.dev/internal/serving is the one for revision metrics.
        - name: METRICS_DOMAIN
          value: knative.dev/internal/serving
        securityContext:
          allowPrivilegeEscalation: false
      - name: autoscaler
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: knative.dev/serving/cmd/autoscaler
        readinessProbe:
          httpGet:
            # The path does not matter, we look for the kubelet user-agent
            # (or our header below)
            path: /healthz
            port: 8080
            httpHeaders:
            # Istio with mTLS strips the Kubelet user-agent, so pass a header too.
            - name: k-kubelet-probe
              value: "autoscaler"
        livenessProbe:
          httpGet:
            # The path does not matter, we look for kubelet probe headers.
            path: /healthz
            port: 8080
            httpHeaders:
            # Istio with mTLS strips the Kubelet user-agent, so pass a header too.
            - name: k-kubelet-probe
              value: "autoscaler"
        resources:
          # Request 2x what we saw running e2e
          requests:
            cpu: 30m
            memory: 40Mi
          # Limit to 10x the request (20x the observed peak during e2e)
          limits:
            cpu: 300m
            memory: 400Mi
        ports:
        - name: websocket
          containerPort: 8080
        - name: metrics
          containerPort: 9090
        - name: custom-metrics
          containerPort: 8443
        - name: profiling
          containerPort: 8009
        args:
        - "--secure-port=8443"
        - "--cert-dir=/tmp"
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        # Used for Stackdriver only.
        - name: METRICS_DOMAIN
          value: knative.dev/serving
        securityContext:
          allowPrivilegeEscalation: false
      - name: webhook
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: knative.dev/serving/cmd/webhook
        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8010
        resources:
          # Request 2x what we saw running e2e
          requests:
            cpu: 20m
            memory: 20Mi
          # Limit to 10x the request (20x the observed peak during e2e)
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: knative.dev/serving
        securityContext:
          allowPrivilegeEscalation: false
      - name: kourier-control
        image: quay.io/3scale/kourier:v0.3.3
        resources: {}
        env:
        - name: CERTS_SECRET_NAMESPACE
          value: ""
        - name: CERTS_SECRET_NAME
          value: ""
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace